### ISSUE TITLE
Authentication support

### ISSUE THREAD

**Issue by pfreixes** [acsylla/acsylla#11]
We must provide a way for allowing the user to use an authentication mode when the user connects to the cluster by using the primitives provided by the CPP Driver [1]

# Output expected

When the user connects to a cluster can provide credentials for authenticating 

[1] https://docs.datastax.com/en/developer/cpp-driver/2.15/api/struct.CassAuthenticator/

**Comment by whiteluna** [comment]
Added plain text authentication in this commit https://github.com/acsylla/acsylla/commit/d6256ed225882c9ddb81680d4a62c5b088b6c1a0

**Comment by pfreixes** [comment]
Ill close this one as done, we would need to provide SSL support
