### ISSUE TITLE
Provide result list utility

### ISSUE THREAD

**Issue by pfreixes** [acsylla/acsylla#45]
Once this has been addressed [1] and types are no longer required we can provide to Acsylla a commodity for iterating for all of the results and columns reducing the boilerplate needed.

A new interface could be implemented, under the Python domain, which would take as an input a Result object [2] and would allow you to iterate over the rows of a result returning a list of tuples, where each tuple would be composed of the name of the column and the value.

The same could be implemented but returning a dictionary, where keys would be the name of the column and value would be the name of the value.

For anything else - like checking pagination - the user would need to still use the API provided by the `Result` object.

For doing so a new primitive would need to be implemented under the `Result` object for returning all column names, this can be achieved by using a combo of `cass_result_column_name ` and `cass_result_column_count`.  The column value can be later gathered using the new `Row.column_value` method [3]

[1] https://github.com/pfreixes/acsylla/issues
[2] https://github.com/pfreixes/acsylla/blob/master/acsylla/_cython/result/result.pyx#L1
[3] https://github.com/pfreixes/acsylla/pull/44/files#diff-bdcc5e3edd11f59e858bdf1764ec95468c8928ad93a228b3fdcd893a0f61b516R20

**Comment by whiteluna** [comment]
@pfreixes @all what do you think about this
```python
import asyncio
import acsylla


async def main():
    cluster = acsylla.create_cluster(['localhost'])
    session = await cluster.create_session(keyspace="acsylla")
    prepared = await session.create_prepared("SELECT id, value FROM test")
    statement = prepared.bind(page_size=10)
    result = await session.execute(statement)
    while result.count():
        # We can iterate over result
        for row in result:
            # Also we can iterate over row
            for column, value in row:
                print(column, value)
                # id 1649
                # value 1649
            # or just list(row)
            print(list(row))
            # [('id', 1649), ('value', 1649)]
            # We can get row as dict
            print(row.as_dict())
            # or just
            print(dict(row))
            # {'id': 1649, 'value': 1649}
            print(row.as_list())
            # [1649, 1649]
            print(row.as_tuple())
            # (1649, 1649)
            # get value by column name
            print(row.column_value("value"))
            # 1649
            # get value by column index
            print(row.column_value_by_index(1))
            # 1649

        # Paging
        if result.has_more_pages():
            # add set_page_state method to statement
            statement.set_page_state(result.page_state())
            result = await session.execute(statement)
        else:
            break

    await session.close()


if __name__ == '__main__':
    asyncio.run(main())
```

For example I pushed branch with this changes https://github.com/acsylla/acsylla/tree/issues-45

**Comment by whiteluna** [comment]
We can add wrapper method get_all_pages to result object for iterate over all pages if needed, code above may changed by
```python
for row in result.get_all_pages():
    ...
```

**Comment by pfreixes** [comment]
👏  👏  awesome .... ready to open a PR?

**Comment by whiteluna** [comment]
@pfreixes I want to add some tests then i make pull request
