### ISSUE TITLE
Spelling: ascylla or acsylla?

### ISSUE THREAD

**Issue by dimaqq** [acsylla/acsylla#65]
Is it `ascylla` as in "async-scylla", or `acsylla` maybe "async client sylla?"

The github project is `acsylla`, yet the README mentions `ascylla`.

I, for one, am very confused 🙈

**Comment by pfreixes** [comment]
There is a typo in the README, should be `acsylla` .... its a composition of `async` + `cassandra` + `scylla` words.

Please feel free to create a PR!

**Comment by whiteluna** [comment]
I'll fixed this in my current pull request, don't worry)))
