### ISSUE TITLE
Python 3.11 compatibility ?

### ISSUE THREAD

**Issue by TheBeardedRaspberry** [acsylla/acsylla#67]
Hello !

There is currently no acsylla package available for Python 3.11. It looks like you are preparing to release 0.1.8a, I'm wondering if it will be compatible with 3.11 ?

Thank you !

**Comment by pfreixes** [comment]
Project is open to any external contributor, adding support for Python 3.11 should be doable, would you like to create a PR for this?

**Comment by whiteluna** [comment]
At this time acsylla does not compile at Python 3.11.0rc2. After stable release python 3.11 we will add support.

**Comment by TheBeardedRaspberry** [comment]
I could give it a jab, but I'm really not sure where to start, it would by my first cython project. I was asking because 3.11.0 got out yesterday :) I'll try compiling it in a docker container.

This is a bit out of scope of this issue's title, but out of curiosity, what do you think will be the future of acsylla after ScyllaDB release a new python driver based on their Rust one ? Their old driver based on Datastax is not asyncio capable, but if the new one based on Rust works, what are your thoughts on that ?

**Comment by whiteluna** [comment]
More drivers, more fun!)

**Comment by whiteluna** [comment]
@TheBeardedRaspberry Next release will available package for Python 3.11.  If you can't wait you can build your own wheel from master branch. See https://github.com/acsylla/acsylla/blob/master/README.md#build-your-own-package

**Comment by TheBeardedRaspberry** [comment]
Wow that's really awesome !
