### ISSUE TITLE
Promote Mor as official maintainer of Acsylla

### ISSUE THREAD

**Issue by pfreixes** [acsylla/acsylla#69]
I would like to recognise the work made by @whiteluna and promote him as official maintainer of `acsylla`, in practical terms it means that he will get the role of maintainer of this project, being able to merge PRs, create new versions, and so son.

WDYT @whiteluna ?

**Comment by whiteluna** [comment]
@pfreixes Thanks!

**Comment by pfreixes** [comment]
done
