### ISSUE TITLE
Return type discussion

### ISSUE THREAD

**Issue by whiteluna** [acsylla/acsylla#79]
Currently `acsylla.Result` map some native CQL data types to python datatype for example  SQL `timestamp` mapping to python `datetime.datetime` etc. This is not good in some situation for  example `cpp-driver` returns CQL type `time` in nanoseconds precision but python `datetime.time` have microseconds precision. 

@all what do you think about adding settings to map python datatypes or return as is? We can add settings to `acsylla.Session` level and/or `acsylla.Statement` or `acsylla.Result` . By default we can map `datetime`,  `time`,  `date`,  `timedelta` and `Decimal` values.

**Comment by pfreixes** [comment]
Im concerned on exposing a map that can be too heavy to understand, if we would have multiple implementations for the different types might make sense - do we have them?. 

Another options that I can see are:

- Make a breaking change and return a "native" type with nanosecond support
- Add a new keyword for any of the interfaces that you mention for configuring returning nanosecond resolution, so returning a new type

Thoughts?

**Comment by whiteluna** [comment]
I think the best solution will be if we add keyword like `return_native_type=False` to `Session` and `Statement`

**Comment by whiteluna** [comment]
Or maybe only for `Result` ?

```python
result = await session.execute(statement)
result.native_type(True) # will return raw values e.g. milliseconds since Epoch for `timestamp` , seconds since Epoch for `date`, number of nanoseconds since midnight for `time` and tuple of (month, days, nanoseconds) for `duration`
for row in result:
    ...
````

**Comment by pfreixes** [comment]
i guess that we could do something like:

```python
result_with_native_types = await session.execute(statement, native_types=true)
```

Since from my undestanding the result would use one or the other, but not both of them at the same time

WDYT?

**Comment by whiteluna** [comment]
Ok I'll do it soon!

**Comment by whiteluna** [comment]
sorry
