### ISSUE TITLE
Unable to install acsylla on python 3.8.16 on mac OS

### ISSUE THREAD

**Issue by hitesh770** [acsylla/acsylla#82]
Getting following error

Could not find a version that satisfies the requirement acsylla

**Comment by hitesh770** [comment]
@whiteluna Could you please help.

**Comment by whiteluna** [comment]
@hitesh770 Can you provide more info, please?

**Comment by whiteluna** [comment]
закрою

**Comment by hitesh770** [comment]
This issue is happing on mac os, when i trying to install getting following error

hitesh.vishal@hiteshs-mbp Desktop % pip install acsylla
ERROR: Could not find a version that satisfies the requirement acsylla (from versions: none)
ERROR: No matching distribution found for acsylla
