### ISSUE TITLE
How to combine cassandra pagination with grpc service?

### ISSUE THREAD

**Issue by garvenlee** [acsylla/acsylla#84]
Assume user sends a http request to gateway for his all history messages, gateway then schedules a grpc call to CassandraService. It’s bad to return all data to user at once, I want to use pagination in cassandra. It can improve the performance.

I see the usage of pagination in acsylla is based on async generator. But it requires the front can receive data continuously.  If GrpcService is introduced, considering that synchronous io is unstable, what’s the solution to implement the above request with cassandra pagination?

**Comment by whiteluna** [comment]
RTFM?
