### ISSUE TITLE
Support for big int - "Expected 8 or 0 byte long (4)"

### ISSUE THREAD

**Issue by mvallebr** [acsylla/acsylla#86]
Hi, 

I am using ascylla to communicate with Cassandra 3.11, given it's a pet project and I like Scylla DB a lot, but I can't find a managed service for 5 USD a month for now, as I can for Cassandra. Not relevant, but just to state that.

I have the following column family in my cluster:

```cql
CREATE TABLE IF NOT EXISTS post_like_count (
    post_id bigint,
    num_likes counter,
    PRIMARY KEY (post_id)
);
```

and I have a `cassandra.py` script with the following function:

```python
async def like_count(cs_session: ac.Session, post_id: int) -> bool:
    statement = ac.create_statement(
        "select num_likes from post_like_count where post_id = ?", parameters=1
    )
    statement.bind_list([post_id])
    result = await cs_session.execute(statement)
    row = result.first()
    value = row.column_value("num_likes")
    return value
```

When I try to execute it, this is what I get:
```
           '"/home/mvallebr/git/youread/youread-backend/youread/service/cassandra.py", '
           'line 74, in like_count\n'
           '    result = await cs_session.execute(statement)\n'
           '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
           '  File "acsylla/_cython/session/session.pyx", line 123, in '
           'execute\n'
           '  File "acsylla/_cython/errors.pyx", line 135, in '
           'acsylla._cython.cyacsylla.raise_if_error\n'
           'acsylla._cython.cyacsylla.CassErrorServerInvalidQuery: Invalid '
           'query: Expected 8 or 0 byte long (4)\n',
```

I understand the problem is that post_id was defined as bigint, but when the statement is executed it sends the syntax for a 32 bit int.
python 3 doesn't differenciate between short and long, so I must somehow tell ascylla that it's a long. 

Is it possible currently? Or is this something unsupported?

**Comment by whiteluna** [comment]
Hi, Can you provide full snippet to reproduce this?

**Comment by whiteluna** [comment]
Уважай мое время

**Comment by whiteluna** [comment]
In other words, all our tests seem to not work, so please fix it; we can make mistakes too.

**Comment by whiteluna** [comment]
хуйню мне чат перевел, иди нахуй

**Comment by mvallebr** [comment]
`docker-compose.yaml` file:

```
services:
  cassandra:
    image: cassandra:3.11.10
    environment:
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - HEAP_NEWSIZE=64M
      - MAX_HEAP_SIZE=64M
    ports:
      - "9042:9042" 
```

You can run cassandra locally with `docker compose run -P cassandra`

Once cassandra is running, you can run this unit test using pytest with support for asyncio:

```python
import acsylla as ac
import pytest
import pytest_asyncio


@pytest_asyncio.fixture
async def cassandra_session_local():
    cluster = ac.create_cluster(
        "localhost",
        port=int(9042),
        username="cassandra",
        password="cassandra",
    )
    session = await cluster.create_session()
    return session


@pytest_asyncio.fixture
async def recreate_cassandra_keyspace_local(cassandra_session_local):
    test_keyspace = "issue86_test"
    # Drop the existing keyspace
    await cassandra_session_local.execute(
        ac.create_statement(f"DROP KEYSPACE IF EXISTS  {test_keyspace}")
    )

    # Create a new keyspace
    await cassandra_session_local.execute(
        ac.create_statement(
            f"CREATE KEYSPACE {test_keyspace} WITH REPLICATION = {{ 'class' : 'SimpleStrategy', 'replication_factor' : 1 }}"
        )
    )
    # Use the new keyspace
    await cassandra_session_local.set_keyspace(test_keyspace)
    # Execute the DDL script
    ddl_stmt = """CREATE TABLE IF NOT EXISTS post_like_count (
        post_id bigint,
        num_likes counter,
        PRIMARY KEY (post_id)
    )"""
    await cassandra_session_local.execute(ac.create_statement(ddl_stmt))


@pytest.mark.asyncio
async def test_bigint_problem_scylla(recreate_cassandra_keyspace_local, cassandra_session_local):
    test_keyspace = "issue86_test"
    await cassandra_session_local.set_keyspace(test_keyspace)

    # Increment the counter
    update_stmt = """UPDATE post_like_count SET num_likes = num_likes + 1 WHERE post_id = 1"""
    await cassandra_session_local.execute(ac.create_statement(update_stmt))

    # Read the row
    statement = ac.create_statement(
        "select num_likes from post_like_count where post_id = ?", parameters=1
    )
    statement.bind_list([1])
    result = await cassandra_session_local.execute(statement)
    row = result.first()
    value = row.column_value("num_likes")
    print("value: ", value)
```

When post id is `bigint` , as shown, this is the result:

```

        # Read the row
        statement = ac.create_statement(
            "select num_likes from post_like_count where post_id = ?", parameters=1
        )
        statement.bind_list([1])
>       result = await cassandra_session_local.execute(statement)

test_bigint_problem_scylla.py:57: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
acsylla/_cython/session/session.pyx:123: in execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   acsylla._cython.cyacsylla.CassErrorServerInvalidQuery: Invalid query: Expected 8 or 0 byte long (4)

acsylla/_cython/errors.pyx:135: CassErrorServerInvalidQuery
```

If you change from `bigint` to just `int`, as:
```
ddl_stmt = """CREATE TABLE IF NOT EXISTS post_like_count (
        post_id int,
        num_likes counter,
        PRIMARY KEY (post_id)
    )"""
```

The test passes. 

Please let me know if this is enough or whether you need anything else to reproduce the problem.

**Comment by mvallebr** [comment]
> In other words, all our tests seem to not work, so please fix it; we can make mistakes too.

I can try to do that, as it's not urgent - but I will probably take some time to familiarise myself with the code. If it's something tricky and you don't have time to fix it, I would be thankful if you could point to the parts of the code which tests the execution of such statements. I won't promise to do any contribution quickly though, but I could try to do it in a month or so.

I found [test_statement](https://github.com/acsylla/acsylla/blob/master/tests/test_statement.py), but it doesn't seem to be the right place, as the bind itself works... The problem happens when the final CQL is assembled during the call to `execute`, I *guess* it's not putting the `L` after the int value in the generated CQL sent in the request. 

I couldn't find the code that generates the final CQL though.

Anyway - I just opened this issue to inform about it and contribute somehow - I can survive with int type until my app has more than some billions of posts, this will take a while. Feel free to close the issue if you think it's not worth solving it.

**Comment by pfreixes** [comment]
Im wondering if we have an issue with the `bigints` when using none prepared statements, at least looking to our [test suite](https://github.com/acsylla/acsylla/blob/master/tests/test_row.py#L94) seems that they are using prepared statements for checking that bigints are working properly.

@mvallebr you could try this workaround, Im hoping that this should circumvent the issue.

**Comment by mvallebr** [comment]
Yes, I can confirm the test below passes with bigint.

```

@pytest.mark.asyncio
async def test_bigint_problem_scylla_using_prepared(recreate_cassandra_keyspace_local, cassandra_session_local):
    test_keyspace = "issue86_test"
    await cassandra_session_local.set_keyspace(test_keyspace)

    # Increment the counter
    update_stmt = """UPDATE post_like_count SET num_likes = num_likes + 1 WHERE post_id = 1"""
    await cassandra_session_local.execute(ac.create_statement(update_stmt))

    statement = await cassandra_session_local.create_prepared("select num_likes from post_like_count where post_id = ?")
    prepared = statement.bind()
    prepared.bind(0, 1)
    result = await cassandra_session_local.execute(prepared)
    row = result.first()
    value = row.column_value("num_likes")
    print("value: ", value)
```

It makes sense, as the prepared statement is probably getting the information from the session about the column. The statement works statically and it doesn't have such info available. It would probably be nice to have a `bind_bigint` method available for statements, or something like `bind_list([BigInt(1)])` - but I don't need it, the prepared statement solution sorts it for me.

Feel free to close the issue if you want.

**Comment by pfreixes** [comment]
We can keep it open since this is bug that we must fix, glad that the workaround worked!

Would you like to work on a patch for the issue?

**Comment by mvallebr** [comment]
Well, I don't have the time right now, but if the issue is still open in 1 month time, then I would be happy to - it would be a nice experience
But I can't commit though, so please don't hold anything for me if it becomes a priority

**Comment by whiteluna** [comment]
A high performance Python Asyncio client library for Cassandra and ScyllaDB
