### ISSUE TITLE
Mac the wheel is broken

### ISSUE THREAD

**Issue by Thaysfsil** [acsylla/acsylla#88]
Hello,

I am encountering an issue when attempting to install the Acsylla package on MacOS. Despite following the recommended installation steps, the process consistently fails.

**Steps to Reproduce**
Run the following commands on MacOS:
```sh
brew install libuv openssl
pip install acsylla
```
Observe the error messages:
```sh
ERROR: Could not find a version that satisfies the requirement acsylla (from versions: none)
ERROR: No matching distribution found for acsylla
```

**Additional Information**
I have tried using different Python versions, but the error persists.
I also attempted to install Acsylla directly from a .whl file, but encountered the same error.

Any assistance in resolving this issue would be appreciated. Thank you all!

**Comment by pfreixes** [comment]
Could you give it a try? I managed to have the mac os wheels for different architectures

```
pip3 install acsylla
Defaulting to user installation because normal site-packages is not writeable
Collecting acsylla
  Downloading acsylla-0.2.0-cp39-cp39-macosx_10_9_universal2.whl.metadata (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.4/52.4 kB 585.8 kB/s eta 0:00:00
Downloading acsylla-0.2.0-cp39-cp39-macosx_10_9_universal2.whl (4.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 1.7 MB/s eta 0:00:00
Installing collected packages: acsylla
Successfully installed acsylla-0.2.0

[notice] A new release of pip is available: 23.3.1 -> 24.1.1
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip
```

**Comment by Thaysfsil** [comment]
It did work, thank you 🚀 🚀

**Comment by pfreixes** [comment]
closing this one
